/*
	Mod Support
	Authors: ChimpanG
*/

-----------------------------------------------
-- CSE
-----------------------------------------------

CREATE TABLE IF NOT EXISTS ModCheck
	(
	ModType					TEXT		NOT NULL,
	Active					BOOLEAN		DEFAULT 1,

	PRIMARY KEY	(ModType)			
	);

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_SCIENTIFIC_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_SCIENTIFIC_TIER_4'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_CULTURAL_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_CULTURAL_TIER_4'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_TRADE_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_TRADE_TIER_4'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_RELIGIOUS_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_RELIGIOUS_TIER_4'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_MILITARISTIC_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_MILITARISTIC_TIER_4'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_INDUSTRIAL_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_INDUSTRIAL_TIER_4'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_SCIENTIFIC_TIER_4', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_4'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_CULTURAL_TIER_4', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_4'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_TRADE_TIER_4', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_4'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_RELIGIOUS_TIER_4', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_4'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_MILITARISTIC_TIER_4', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_4'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_INDUSTRIAL_TIER_4', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_4'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_SCIENTIFIC_TIER_1', 'YieldType', 'YIELD_SCIENCE'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_SCIENTIFIC_TIER_1', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_CULTURAL_TIER_1', 'YieldType', 'YIELD_CULTURE'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_CULTURAL_TIER_1', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_TRADE_TIER_1', 'YieldType', 'YIELD_GOLD'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_TRADE_TIER_1', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_RELIGIOUS_TIER_1', 'YieldType', 'YIELD_FAITH'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_RELIGIOUS_TIER_1', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_MILITARISTIC_TIER_1', 'YieldType', 'YIELD_PRODUCTION'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_MILITARISTIC_TIER_1', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_INDUSTRIAL_TIER_1', 'YieldType', 'YIELD_PRODUCTION'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_INDUSTRIAL_TIER_1', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType)
SELECT	'REQSET_CVS_MALAYSIA_TIER_4',
		'REQUIREMENTSET_TEST_ALL'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
SELECT	'REQSET_CVS_MALAYSIA_TIER_4',
		'REQ_CVS_MALAYSIA_PLAYER_IS_MALAYSIA'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
SELECT	'REQSET_CVS_MALAYSIA_TIER_4',
		'REQ_CVS_MALAYSIA_CS_FOURTH_TIER'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
SELECT	'REQSET_CVS_MALAYSIA_TIER_4',
		'REQUIRES_PLAYER_IS_SUZERAIN'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO Requirements (RequirementId, RequirementType, Inverse)
SELECT	'REQ_CVS_MALAYSIA_CS_FOURTH_TIER',
		'REQUIREMENT_PLAYER_HAS_GIVEN_INFLUENCE_TOKENS',
		0
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO RequirementArguments (RequirementId, Name, Value)
SELECT	'REQ_CVS_MALAYSIA_CS_FOURTH_TIER',
		'MinimumTokens',
		10
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

-----------------------------------------------
-- CSE MARITIME
-----------------------------------------------

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_MARITIME_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_MARITIME_TIER_1'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_MARITIME');

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_MARITIME_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_MARITIME_TIER_2'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_MARITIME');

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_MARITIME_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_MARITIME_TIER_3'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_MARITIME');

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_MARITIME_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_MARITIME_TIER_4'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_MARITIME');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_MARITIME_TIER_1', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_1'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_MARITIME');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_MARITIME_TIER_2', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_2'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_MARITIME');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_MARITIME_TIER_3', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_3'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_MARITIME');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_MARITIME_TIER_4', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_4'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_MARITIME');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_MARITIME_TIER_1', 'YieldType', 'YIELD_FOOD'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_MARITIME_TIER_1', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_MARITIME');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_MARITIME_TIER_2', 'YieldType', 'YIELD_FOOD'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_MARITIME');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_MARITIME_TIER_2', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_MARITIME');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_MARITIME_TIER_3', 'YieldType', 'YIELD_FOOD'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_MARITIME');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_MARITIME_TIER_3', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_MARITIME');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_MARITIME_TIER_4', 'YieldType', 'YIELD_FOOD'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_MARITIME');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_MARITIME_TIER_4', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_MARITIME');

-----------------------------------------------
-- CSE AGRICULTURAL
-----------------------------------------------

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_AGRICULTURAL_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_AGRICULTURAL_TIER_1'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_AGRICULTURAL');

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_AGRICULTURAL_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_AGRICULTURAL_TIER_2'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_AGRICULTURAL');

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_AGRICULTURAL_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_AGRICULTURAL_TIER_3'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_AGRICULTURAL');

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_AGRICULTURAL_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_AGRICULTURAL_TIER_4'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_AGRICULTURAL');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_AGRICULTURAL_TIER_1', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_1'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_AGRICULTURAL');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_AGRICULTURAL_TIER_2', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_2'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_AGRICULTURAL');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_AGRICULTURAL_TIER_3', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_3'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_AGRICULTURAL');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_AGRICULTURAL_TIER_4', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_4'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_AGRICULTURAL');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_AGRICULTURAL_TIER_1', 'YieldType', 'YIELD_FOOD'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_AGRICULTURAL');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_AGRICULTURAL_TIER_1', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_AGRICULTURAL');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_AGRICULTURAL_TIER_2', 'YieldType', 'YIELD_FOOD'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_AGRICULTURAL');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_AGRICULTURAL_TIER_2', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_AGRICULTURAL');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_AGRICULTURAL_TIER_3', 'YieldType', 'YIELD_FOOD'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_AGRICULTURAL');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_AGRICULTURAL_TIER_3', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_AGRICULTURAL');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_AGRICULTURAL_TIER_4', 'YieldType', 'YIELD_FOOD'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_AGRICULTURAL');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_AGRICULTURAL_TIER_4', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_AGRICULTURAL');

-----------------------------------------------
-- CSE ENTERTAINMENT
-----------------------------------------------

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_ENTERTAINMENT_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_ENTERTAINMENT_TIER_1'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_ENTERTAINMENT');

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_ENTERTAINMENT_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_ENTERTAINMENT_TIER_2'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_ENTERTAINMENT');

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_ENTERTAINMENT_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_ENTERTAINMENT_TIER_3'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_ENTERTAINMENT');

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_ENTERTAINMENT_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_ENTERTAINMENT_TIER_4'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_ENTERTAINMENT');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_ENTERTAINMENT_TIER_1', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_1'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_ENTERTAINMENT');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_ENTERTAINMENT_TIER_2', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_2'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_ENTERTAINMENT');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_ENTERTAINMENT_TIER_3', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_3'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_ENTERTAINMENT');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_ENTERTAINMENT_TIER_4', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_4'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_ENTERTAINMENT');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_ENTERTAINMENT_TIER_1', 'YieldType', 'YIELD_GOLD'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_ENTERTAINMENT');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_ENTERTAINMENT_TIER_1', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_ENTERTAINMENT');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_ENTERTAINMENT_TIER_2', 'YieldType', 'YIELD_GOLD'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_ENTERTAINMENT');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_ENTERTAINMENT_TIER_2', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_ENTERTAINMENT');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_ENTERTAINMENT_TIER_3', 'YieldType', 'YIELD_GOLD'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_ENTERTAINMENT');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_ENTERTAINMENT_TIER_3', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_ENTERTAINMENT');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_ENTERTAINMENT_TIER_4', 'YieldType', 'YIELD_GOLD'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_ENTERTAINMENT');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_ENTERTAINMENT_TIER_4', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_ENTERTAINMENT');

-----------------------------------------------
-- CSE CONSULAR
-----------------------------------------------

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_CONSULAR_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_CONSULAR_TIER_1'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_CONSULAR');

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_CONSULAR_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_CONSULAR_TIER_2'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_CONSULAR');

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_CONSULAR_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_CONSULAR_TIER_3'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_CONSULAR');

INSERT INTO TraitModifiers (TraitType, ModifierId)
SELECT	'MINOR_CIV_CONSULAR_TRAIT', 'MODIFIER_CVS_MALAYSIA_UA_CONSULAR_TIER_4'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_CONSULAR');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_CONSULAR_TIER_1', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_1'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_CONSULAR');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_CONSULAR_TIER_2', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_2'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_CONSULAR');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_CONSULAR_TIER_3', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_3'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_CONSULAR');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_CONSULAR_TIER_4', 'MODTYPE_CVS_MALAYSIA_UA_TRADE_TO_OTHERS', 'REQSET_CVS_MALAYSIA_TIER_4'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_CONSULAR');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_CONSULAR_TIER_1', 'YieldType', 'YIELD_GOLD'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CITY_STATES_EXPANDED');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_CONSULAR_TIER_1', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_CONSULAR');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_CONSULAR_TIER_2', 'YieldType', 'YIELD_GOLD'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_CONSULAR');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_CONSULAR_TIER_2', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_CONSULAR');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_CONSULAR_TIER_3', 'YieldType', 'YIELD_GOLD'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_CONSULAR');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_CONSULAR_TIER_3', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_CONSULAR');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_CONSULAR_TIER_4', 'YieldType', 'YIELD_GOLD'
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_CONSULAR');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODIFIER_CVS_MALAYSIA_UA_CONSULAR_TIER_4', 'Amount', 1
WHERE EXISTS (SELECT * FROM ModCheck WHERE ModType = 'CSE_CONSULAR');

-----------------------------------------------
-- RwF
-----------------------------------------------

CREATE TABLE IF NOT EXISTS 
	Civilization_Titles (
	CivilizationType  				text 		 		default null,
	GovernmentType					text 	 			default null,
	LeaderTitle						text				default null,
	PolicyType  					text 		 		default null);

CREATE TABLE IF NOT EXISTS 
	Civilization_StartingGovernment (
	CivilizationType  				text 		 		default null,
	GovernmentType					text 				default null,
	LeaderType						text				default null);	

INSERT INTO Civilization_Titles
		(CivilizationType, 				GovernmentType, 							LeaderTitle															)
VALUES	('CIVILIZATION_CVS_MALAYSIA',	'GOVERNMENT_CHIEFDOM',						'LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_CVS_MALAYSIA'				),
		('CIVILIZATION_CVS_MALAYSIA',	'GOVERNMENT_JFD_HORDE',						'LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_MALAYSIA'				),
		('CIVILIZATION_CVS_MALAYSIA',	'GOVERNMENT_JFD_POLIS',						'LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_CVS_MALAYSIA'				),
		('CIVILIZATION_CVS_MALAYSIA',	'GOVERNMENT_AUTOCRACY',						'LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_CVS_MALAYSIA'			),
		('CIVILIZATION_CVS_MALAYSIA',	'GOVERNMENT_OLIGARCHY',						'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_MALAYSIA'			), 
		('CIVILIZATION_CVS_MALAYSIA',	'GOVERNMENT_CLASSICAL_REPUBLIC',			'LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_CVS_MALAYSIA'	),
		('CIVILIZATION_CVS_MALAYSIA',	'GOVERNMENT_MONARCHY',						'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_MALAYSIA'				),
		('CIVILIZATION_CVS_MALAYSIA',	'GOVERNMENT_MERCHANT_REPUBLIC',				'LOC_GOVERNMENT_JFD_REPUBLIC_LEADER_TITLE_CVS_MALAYSIA'				),
		('CIVILIZATION_CVS_MALAYSIA',	'GOVERNMENT_JFD_ABSOLUTE_MONARCHY',			'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_MALAYSIA'				),
		('CIVILIZATION_CVS_MALAYSIA',	'GOVERNMENT_JFD_CONSTITUTIONAL_MONARCHY',	'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_MALAYSIA'				),
		('CIVILIZATION_CVS_MALAYSIA',	'GOVERNMENT_JFD_NOBLE_REPUBLIC',			'LOC_GOVERNMENT_JFD_REPUBLIC_LEADER_TITLE_CVS_MALAYSIA'				),
		('CIVILIZATION_CVS_MALAYSIA',	'GOVERNMENT_DEMOCRACY',						'LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_CVS_MALAYSIA'	),
		('CIVILIZATION_CVS_MALAYSIA',	'GOVERNMENT_COMMUNISM',						'LOC_GOVERNMENT_JFD_REPUBLIC_LEADER_TITLE_CVS_MALAYSIA'				),
		('CIVILIZATION_CVS_MALAYSIA',	'GOVERNMENT_FASCISM',						'LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_MALAYSIA'				);

DELETE FROM Civilization_Titles WHERE CivilizationType = 'CIVILIZATION_CVS_MALAYSIA' AND GovernmentType IS NOT NULL AND GovernmentType NOT IN (SELECT GovernmentType FROM Governments);
DELETE FROM Civilization_Titles WHERE CivilizationType = 'CIVILIZATION_CVS_MALAYSIA' AND PolicyType IS NOT NULL AND PolicyType NOT IN (SELECT PolicyType FROM Policies);

INSERT INTO	Civilization_StartingGovernment
		(CivilizationType,				GovernmentType			)
VALUES	('CIVILIZATION_CVS_MALAYSIA',	'GOVERNMENT_JFD_POLIS'	);
