/*
	Strategy
	Authors: ChimpanG
*/

-----------------------------------------------
-- AiListTypes
-----------------------------------------------

INSERT INTO AiListTypes
		(ListType								)
VALUES 	('LEADER_CVS_TUN_PERAK_TECHS'			),
		('LEADER_CVS_TUN_PERAK_CIVICS'			),
		('LEADER_CVS_TUN_PERAK_DISTRICTS'		),
		('LEADER_CVS_TUN_PERAK_BUILDINGS'		),
		('LEADER_CVS_TUN_PERAK_PROJECTS'		),
		('LEADER_CVS_TUN_PERAK_DIPLOMACY'		),
		('LEADER_CVS_TUN_PERAK_TACTICS'			),
		('LEADER_CVS_TUN_PERAK_EXPANSION'		),
		('LEADER_CVS_TUN_PERAK_PSUEDOS'			),
		('LEADER_CVS_TUN_PERAK_YIELDS'			);

-----------------------------------------------
-- AiLists
-----------------------------------------------

INSERT INTO AiLists
		(ListType,								AgendaType,						System				)
VALUES  ('LEADER_CVS_TUN_PERAK_TECHS',			'TRAIT_AGENDA_CVS_TUN_PERAK',	'Technologies'		),
		('LEADER_CVS_TUN_PERAK_CIVICS',			'TRAIT_AGENDA_CVS_TUN_PERAK',	'Civics'			),
		('LEADER_CVS_TUN_PERAK_DISTRICTS',		'TRAIT_AGENDA_CVS_TUN_PERAK',	'Districts'			),
		('LEADER_CVS_TUN_PERAK_BUILDINGS',		'TRAIT_AGENDA_CVS_TUN_PERAK',	'Buildings'			),
		('LEADER_CVS_TUN_PERAK_PROJECTS',		'TRAIT_AGENDA_CVS_TUN_PERAK',	'Projects'			),
		('LEADER_CVS_TUN_PERAK_DIPLOMACY',		'TRAIT_AGENDA_CVS_TUN_PERAK',	'DiplomaticActions'	),
		('LEADER_CVS_TUN_PERAK_TACTICS',		'TRAIT_AGENDA_CVS_TUN_PERAK',	'Tactics'			),
		('LEADER_CVS_TUN_PERAK_EXPANSION',		'TRAIT_AGENDA_CVS_TUN_PERAK',	'PlotEvaluations'	),
		('LEADER_CVS_TUN_PERAK_PSUEDOS',		'TRAIT_AGENDA_CVS_TUN_PERAK',	'PsuedoYields'		),
		('LEADER_CVS_TUN_PERAK_YIELDS',			'TRAIT_AGENDA_CVS_TUN_PERAK',	'Yields'			);
		
-----------------------------------------------
-- AiFavoredItems
-----------------------------------------------

INSERT INTO AiFavoredItems
		(ListType,								Item,										Favored	)
VALUES  -- TECHS
		('LEADER_CVS_TUN_PERAK_TECHS',			'TECH_CURRENCY',							1		),
		('LEADER_CVS_TUN_PERAK_TECHS',			'TECH_MATHEMATICS',							1		),
		('LEADER_CVS_TUN_PERAK_TECHS',			'TECH_BANKING',								1		),
		('LEADER_CVS_TUN_PERAK_TECHS',			'TECH_ECONOMICS',							1		),
		('LEADER_CVS_TUN_PERAK_TECHS',			'TECH_SAILING',								1		),
		('LEADER_CVS_TUN_PERAK_TECHS',			'TECH_CELESTIAL_NAVIGATION',				1		),
		('LEADER_CVS_TUN_PERAK_TECHS',			'TECH_SHIPBUILDING',						1		),
		('LEADER_CVS_TUN_PERAK_TECHS',			'TECH_CARTOGRAPHY',							1		),
		('LEADER_CVS_TUN_PERAK_TECHS',			'TECH_SQUARE_RIGGING',						1		),
		-- CIVICS
		('LEADER_CVS_TUN_PERAK_CIVICS',			'CIVIC_CRAFTMANSHIP',						1		),
		('LEADER_CVS_TUN_PERAK_CIVICS',			'CIVIC_EARLY_EMPIRE',						1		),
		('LEADER_CVS_TUN_PERAK_CIVICS',			'CIVIC_FOREIGN_TRADE',						1		),
		('LEADER_CVS_TUN_PERAK_CIVICS',			'CIVIC_FEUDALISM',							1		),
		('LEADER_CVS_TUN_PERAK_CIVICS',			'CIVIC_NATIONALISM',						1		),
		('LEADER_CVS_TUN_PERAK_CIVICS',			'CIVIC_DIVINE_RIGHT',						1		),
		('LEADER_CVS_TUN_PERAK_CIVICS',			'CIVIC_NAVAL_TRADITION',					1		),
		('LEADER_CVS_TUN_PERAK_CIVICS',			'CIVIC_EXPLORATION',						1		),
		('LEADER_CVS_TUN_PERAK_CIVICS',			'CIVIC_MERCANTILISM',						1		),
		('LEADER_CVS_TUN_PERAK_CIVICS',			'CIVIC_COLONIALISM',						1		),
		('LEADER_CVS_TUN_PERAK_CIVICS',			'CIVIC_URBANIZATION',						1		),
		('LEADER_CVS_TUN_PERAK_CIVICS',			'CIVIC_CULTURAL_HERITAGE',					1		),
		-- DISTRICTS
		('LEADER_CVS_TUN_PERAK_DISTRICTS',		'DISTRICT_COMMERCIAL_HUB',					1		),
		('LEADER_CVS_TUN_PERAK_DISTRICTS',		'DISTRICT_ENCAMPMENT',						1		),
		('LEADER_CVS_TUN_PERAK_DISTRICTS',		'DISTRICT_CVS_MALAYSIA_UI',					1		),
		-- BUILDINGS
		('LEADER_CVS_TUN_PERAK_BUILDINGS',		'BUILDING_MARKET',							1		),
		('LEADER_CVS_TUN_PERAK_BUILDINGS',		'BUILDING_BANK',							1		),
		('LEADER_CVS_TUN_PERAK_BUILDINGS',		'BUILDING_STOCK_EXCHANGE',					1		),
		('LEADER_CVS_TUN_PERAK_BUILDINGS',		'BUILDING_LIGHTHOUSE',						1		),
		('LEADER_CVS_TUN_PERAK_BUILDINGS',		'BUILDING_DRYDOCK',							1		),
		('LEADER_CVS_TUN_PERAK_BUILDINGS',		'BUILDING_SEAPORT',							1		),
		('LEADER_CVS_TUN_PERAK_BUILDINGS',		'BUILDING_BARRACKS',						1		),
		('LEADER_CVS_TUN_PERAK_BUILDINGS',		'BUILDING_ARMORY',							1		),
		('LEADER_CVS_TUN_PERAK_BUILDINGS',		'BUILDING_MILITARY_ACADEMY',				1		),
		-- WONDERS
		('LEADER_CVS_TUN_PERAK_BUILDINGS',		'BUILDING_COLOSSUS',						1		),
		('LEADER_CVS_TUN_PERAK_BUILDINGS',		'BUILDING_PETRA',							1		),
		('LEADER_CVS_TUN_PERAK_BUILDINGS',		'BUILDING_GREAT_ZIMBABWE',					1		),
		('LEADER_CVS_TUN_PERAK_BUILDINGS',		'BUILDING_BIG_BEN',							1		),
		('LEADER_CVS_TUN_PERAK_BUILDINGS',		'BUILDING_GREAT_LIGHTHOUSE',				1		),
		('LEADER_CVS_TUN_PERAK_BUILDINGS',		'BUILDING_VENETIAN_ARSENAL',				1		),
		('LEADER_CVS_TUN_PERAK_BUILDINGS',		'BUILDING_STATUE_LIBERTY',					1		),
		('LEADER_CVS_TUN_PERAK_BUILDINGS',		'BUILDING_HALICARNASSUS_MAUSOLEUM',			1		);
		
INSERT INTO AiFavoredItems
		(ListType,								Item,								Favored,	Value,	StringVal					)
VALUES  -- EXPANSION
		('LEADER_CVS_TUN_PERAK_EXPANSION',		'Specific Resource',				1,			7,		'RESOURCE_WHALES'			),
		('LEADER_CVS_TUN_PERAK_EXPANSION',		'Specific Resource',				1,			7,		'RESOURCE_PEARLS'			),
		('LEADER_CVS_TUN_PERAK_EXPANSION',		'Specific Resource',				1,			7,		'RESOURCE_CRABS'			),
		('LEADER_CVS_TUN_PERAK_EXPANSION',		'Specific Resource',				1,			7,		'RESOURCE_FISH'				),
		('LEADER_CVS_TUN_PERAK_EXPANSION',		'Coastal',							1,			30,		NULL						),
		-- PSUEDOS
		('LEADER_CVS_TUN_PERAK_PSUEDOS',		'PSEUDOYIELD_GPP_MERCHANT',			1,			30,		NULL						),
		('LEADER_CVS_TUN_PERAK_PSUEDOS',		'PSEUDOYIELD_GPP_ADMIRAL',			1,			15,		NULL						),
		('LEADER_CVS_TUN_PERAK_PSUEDOS',		'PSEUDOYIELD_IMPROVEMENT',			1,			5,		NULL						),
		('LEADER_CVS_TUN_PERAK_PSUEDOS',		'PSEUDOYIELD_UNIT_NAVAL_COMBAT',	1,			20,		NULL						),
		('LEADER_CVS_TUN_PERAK_PSUEDOS',		'PSEUDOYIELD_UNIT_TRADE',			1,			2.0,	NULL						);

